### ISSUE TITLE
The API documentation is not available

### ISSUE THREAD

**Issue by GitP4tt** [aspose-cad/Aspose.CAD-for-Java#3]
I'm getting a 404 for every class related doc I wanted to read.
Here you go:
https://apireference.aspose.com/java/cad/com.aspose.cad.fileformats.cad/package-frame

**Comment by mannanfazil** [comment]
@GitP4tt 
We have observed the issue shared by you. We are looking into this issue and will fix this as soon as possible.
Thanks for your cooperation.

**Comment by mannanfazil** [comment]
@GitP4tt 
The issue has been fixed. The API documentation is working fine now.

**Comment by GitP4tt** [comment]
At least this document is still not available.

https://apireference.aspose.com/CadGraphicsDataContainer.html

**Comment by mannanfazil** [comment]
@GitP4tt
Please navigate to this URL:  https://apireference.aspose.com/net/cad/aspose.cad.fileformats.cad.cadobjects/cadgraphicsdatacontainer

We have noted this issue and will update this URL soon. Thanks
